amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    scan_topic: "/scan"
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""   # overridden by launch arg

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # added something
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoal"
        scale: 1.0
      Oscillation:
        plugin: "dwb_critics::Oscillation"
        scale: 1.0
      BaseObstacle:
        plugin: "dwb_critics::BaseObstacle"
        scale: 1.0
      GoalAlign:
        plugin: "dwb_critics::GoalAlign"
        scale: 0.0
      PathAlign:
        plugin: "dwb_critics::PathAlign"
        scale: 5.0
      PathDist:
        plugin: "dwb_critics::PathDist"
        scale: 10.0
      GoalDist:
        plugin: "dwb_critics::GoalDist"
        scale: 10.0
      #end of addition

bt_navigator:
  ros__parameters:
    use_sim_time: true

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["map_server", "amcl", "planner_server", "controller_server", "bt_navigator"]
