slam_toolbox:
  ros__parameters:
    mode: mapping
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    map_update_interval: 2.0
    transform_timeout: 0.5
    resolution: 0.05
    scan_topic: /scan
    use_sim_time: true
